name: LightHouse CI

on:
  push:
    branches: [trunk]
  pull_request:
    branches: ['**']

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [20.x, 18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm i -g @wordpress/env
      - run: wp-env start
      - run: wp-env run cli wp theme activate wp-starter-2024

      # Run Lighthouse CI
      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@v10
        with:
          urls: 
            http://localhost:8888
          budgetPath: .budget.json